before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
 -
  format: tar.gz
  name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
  format_overrides:
    - goos: windows
      format: zip

dockers:
  - image_templates:
      - "ghcr.io/droso-hass/openab:latest"
      - "ghcr.io/droso-hass/openab:{{ .Tag }}"
      - "ghcr.io/droso-hass/openab:v{{ .Major }}"

checksum:
  name_template: 'checksums.txt'