name: release
on:
  push:
    tags:
      - 'v*'
permissions: write-all

jobs:
  # TODO: make tagtag bootcode and karotz_rs
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Build AsyncAPI Docs
        run: |
          npm i -g @asyncapi/cli
          cd docs && asyncapi generate fromTemplate ./asyncapi.yaml @asyncapi/html-template --force-write -o ./dist/api

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
